### ISSUE TITLE
Do you plan to add custom options?

### ISSUE THREAD

**Issue by wzol** [borge12/simple-chat#3]
Example max tokens, temperature etc?

**Comment by awiggins12** [comment]
Yes, definitely.  Next step is to get the api key out of the code.  Then I'll either add those settings or add controls for editing responses.

**Comment by awiggins12** [comment]
I added the settings.  I just added temperature and top p.  

I also added the max token length, but, because it includes the input token length I ran into issues when testing it.  I'll need to get the token length of the conversation and of the input before I can properly implement this as a setting, because I'll need to make sure the max length setting value + sum of all input tokens doesn't exceed 4096.  

What are the settings you were hoping to see?

**Comment by wzol** [comment]
Thank you, I think it would be useful to also have "frequency_penalty," which discourages repetition of generated text; and "presence_penalty," which discourages generating text that does not match any part of the prompt

Also It would be helpful if these would be saved into previous chat sessions, so you can really continue, from where you were.

**Comment by awiggins12** [comment]
Those two have been added now.

**Comment by wzol** [comment]
Thank you, testing it

**Comment by awiggins12** [comment]
I appreciate it.  I really have been having short conversations, so I feel like I haven't tested those adequately.
