### ISSUE TITLE
Is there a way to use this with fine tuned GPT 3.5 model?

### ISSUE THREAD

**Issue by erbill** [borge12/simple-chat#4]
I can test my fine tune on Openai Playground but how can I keep using it with your local layout and functionalities?

**Comment by awiggins12** [comment]
I don't have any experience with the fine-tuned models and I don't know how you access them through the API.  But, I do know from OpenAI's on the chat operation [chat documentation](https://platform.openai.com/docs/api-reference/chat) that only the gpt-3.5-turbo and gpt-3.5-turbo-0301 models are supported with the operation, which cannot be fine tuned.  

So, I think, unfortunately there would need to be a re-write of the app in order to support the other models.

**Comment by erbill** [comment]
Thanks for the clarification. After inspecting chat documentation, I think I was trying to say "embeddings" Providing some extra content -not fine-tuning- and then starting the chat. 

Like one local instance of chat which knows about my favorite musics. Than another chat session which knows my favorite movies. And when I ask a question for each chat session, it considers the small info I've placed in the beginning of the conversation and keeps answering via GPT3.5 ? 
Is that something possible with simple-chat? 

Or maybe can I type longer text in Assistant Behavior part? Is this   {"role": "system", "content": "You are a friendly and helpful teaching assistant. You explain concepts in ///

part? Or what exactly Assistant Behavior makes a difference?
Thanks a lot

**Comment by awiggins12** [comment]
I'm not familiar with how embeddings work in this context.  But, yes, you can add whatever you want into the "assistant behavior" section of the chat (which works off the system role).  If that doesn't seem to be very effective, you can add the text directly into your initial prompt as well.
